In [73]:
import os

import numpy as np

import pandas as pd
pd.set_option('display.max_rows', 10)
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 20)

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

import csv

In [74]:
df = pd.read_csv(os.path.join('.', 'datasets', 'storms.csv.gz'))

In [75]:
df

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,COUNTYNAME,STATE,EVTYPE,BGN_RANGE,BGN_AZI,...,CROPDMGEXP,WFO,STATEOFFIC,ZONENAMES,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS,REFNUM
0,1.0,4/18/1950 0:00:00,130,CST,97.0,MOBILE,AL,TORNADO,0.0,NaN,...,NaN,NaN,NaN,NaN,3040.0,8812.0,3051.0,8806.0,NaN,1.0
1,1.0,4/18/1950 0:00:00,145,CST,3.0,BALDWIN,AL,TORNADO,0.0,NaN,...,NaN,NaN,NaN,NaN,3042.0,8755.0,0.0,0.0,NaN,2.0
2,1.0,2/20/1951 0:00:00,1600,CST,57.0,FAYETTE,AL,TORNADO,0.0,NaN,...,NaN,NaN,NaN,NaN,3340.0,8742.0,0.0,0.0,NaN,3.0
3,1.0,6/8/1951 0:00:00,900,CST,89.0,MADISON,AL,TORNADO,0.0,NaN,...,NaN,NaN,NaN,NaN,3458.0,8626.0,0.0,0.0,NaN,4.0
4,1.0,11/15/1951 0:00:00,1500,CST,43.0,CULLMAN,AL,TORNADO,0.0,NaN,...,NaN,NaN,NaN,NaN,3412.0,8642.0,0.0,0.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902292,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,WYZ007 - 017,WY,HIGH WIND,0.0,NaN,...,K,RIW,"WYOMING, Central and West",OWL CREEK & BRIDGER MOUNTAINS - OWL CREEK & BR...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong cold front moved s...,902293.0
902293,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,MTZ009 - 010,MT,HIGH WIND,0.0,NaN,...,K,TFX,"MONTANA, Central",NORTH ROCKY MOUNTAIN FRONT - NORTH ROCKY MOUNT...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong westerly flow alof...,902294.0
902294,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,AKZ213,AK,HIGH WIND,0.0,NaN,...,K,AFG,"ALASKA, Northern",ST LAWRENCE IS. BERING STRAIT - ST LAWRENCE IS...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,902295.0
902295,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,AKZ202,AK,BLIZZARD,0.0,NaN,...,K,AFG,"ALASKA, Northern",NORTHERN ARCTIC COAST - NORTHERN ARCTIC COAST,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,902296.0
902296,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,ALZ006,AL,HEAVY SNOW,0.0,NaN,...,K,HUN,"ALABAMA, North",MADISON - MADISON,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: An intense upper level low ...,902297.0

In [76]:
df = df.set_index('REFNUM')

In [77]:
df [['STATE','COUNTY']]

         STATE  COUNTY
REFNUM
1.0         AL    97.0
2.0         AL     3.0
3.0         AL    57.0
4.0         AL    89.0
5.0         AL    43.0
...        ...     ...
902293.0    WY     7.0
902294.0    MT     9.0
902295.0    AK   213.0
902296.0    AK   202.0
902297.0    AL     6.0

[902297 rows x 2 columns]

In [78]:
df.columns

Index([u'STATE__', u'BGN_DATE', u'BGN_TIME', u'TIME_ZONE', u'COUNTY',
       u'COUNTYNAME', u'STATE', u'EVTYPE', u'BGN_RANGE', u'BGN_AZI',
       u'BGN_LOCATI', u'END_DATE', u'END_TIME', u'COUNTY_END', u'COUNTYENDN',
       u'END_RANGE', u'END_AZI', u'END_LOCATI', u'LENGTH', u'WIDTH', u'F',
       u'MAG', u'FATALITIES', u'INJURIES', u'PROPDMG', u'PROPDMGEXP',
       u'CROPDMG', u'CROPDMGEXP', u'WFO', u'STATEOFFIC', u'ZONENAMES',
       u'LATITUDE', u'LONGITUDE', u'LATITUDE_E', u'LONGITUDE_', u'REMARKS'],
      dtype='object')

In [79]:
for column in df.columns:
    print column

STATE__
BGN_DATE
BGN_TIME
TIME_ZONE
COUNTY
COUNTYNAME
STATE
EVTYPE
BGN_RANGE
BGN_AZI
BGN_LOCATI
END_DATE
END_TIME
COUNTY_END
COUNTYENDN
END_RANGE
END_AZI
END_LOCATI
LENGTH
WIDTH
F
MAG
FATALITIES
INJURIES
PROPDMG
PROPDMGEXP
CROPDMG
CROPDMGEXP
WFO
STATEOFFIC
ZONENAMES
LATITUDE
LONGITUDE
LATITUDE_E
LONGITUDE_
REMARKS

In [80]:
df[['REMARKS']].dropna()

                                                    REMARKS
REFNUM
187560.0  Light freezing rain coated bridges and overpas...
187561.0  Light snow fell across the northern third of A...
187562.0  A devastating and paralyzing ice storm struck ...
187563.0  Snow and ice combined to close roads across no...
187564.0  What most called the worst winter storm in Ala...
...                                                     ...
902293.0  EPISODE NARRATIVE: A strong cold front moved s...
902294.0  EPISODE NARRATIVE: A strong westerly flow alof...
902295.0  EPISODE NARRATIVE: A 960 mb low over the south...
902296.0  EPISODE NARRATIVE: A 960 mb low over the south...
902297.0  EPISODE NARRATIVE: An intense upper level low ...

[614864 rows x 1 columns]

In [81]:
a = df.isnull().sum()

In [82]:
for column in df.columns:
    print "{:20s} {:2.1f}".format(column, 100. * a[column] / len(df))

STATE__              0.0
BGN_DATE             0.0
BGN_TIME             0.0
TIME_ZONE            0.0
COUNTY               0.0
COUNTYNAME           0.2
STATE                0.0
EVTYPE               0.0
BGN_RANGE            0.0
BGN_AZI              60.7
BGN_LOCATI           31.9
END_DATE             27.0
END_TIME             26.5
COUNTY_END           0.0
COUNTYENDN           100.0
END_RANGE            0.0
END_AZI              80.3
END_LOCATI           55.3
LENGTH               0.0
WIDTH                0.0
F                    93.5
MAG                  0.0
FATALITIES           0.0
INJURIES             0.0
PROPDMG              0.0
PROPDMGEXP           51.6
CROPDMG              0.0
CROPDMGEXP           68.5
WFO                  15.7
STATEOFFIC           27.6
ZONENAMES            65.8
LATITUDE             0.0
LONGITUDE            0.0
LATITUDE_E           0.0
LONGITUDE_           0.0
REMARKS              31.9

In [83]:
pd.crosstab(df.STATE, df.FATALITIES, dropna = False)

FATALITIES,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,57.0,67.0,74.0,75.0,90.0,99.0,114.0,116.0,158.0,583.0
STATE,,,,,,,,,,,,,,,,,,,,,
AK,4343,36,7,1,1,1,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AL,22494,154,33,9,9,9,5,3,1,4,...,0,0,0,0,0,0,0,0,0,0
AM,1871,6,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AN,3243,5,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AR,26869,162,32,13,5,8,3,3,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WA,3207,83,12,4,4,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
WI,19659,88,18,4,4,0,1,1,1,2,...,1,0,0,0,0,0,0,0,0,0
WV,9032,49,12,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
WY,7287,38,4,2,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
XX,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [84]:
df.dropna(axis = 1).columns

Index([u'STATE__', u'BGN_DATE', u'BGN_TIME', u'TIME_ZONE', u'COUNTY', u'STATE',
       u'EVTYPE', u'BGN_RANGE', u'COUNTY_END', u'END_RANGE', u'LENGTH',
       u'WIDTH', u'MAG', u'FATALITIES', u'INJURIES', u'PROPDMG', u'CROPDMG',
       u'LONGITUDE', u'LONGITUDE_'],
      dtype='object')

In [89]:
df[df.duplicated()]

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,COUNTYNAME,STATE,EVTYPE,BGN_RANGE,BGN_AZI,...,CROPDMG,CROPDMGEXP,WFO,STATEOFFIC,ZONENAMES,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS
REFNUM,,,,,,,,,,,,,,,,,,,,,
19.0,1.0,5/10/1952 0:00:00,900,CST,57.0,FAYETTE,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3344.0,8745.0,0.0,0.0,NaN
20.0,1.0,5/10/1952 0:00:00,900,CST,57.0,FAYETTE,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3344.0,8745.0,0.0,0.0,NaN
260.0,1.0,7/4/1960 0:00:00,1750,CST,13.0,BUTLER,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3139.0,8636.0,0.0,0.0,NaN
603.0,1.0,5/14/1967 0:00:00,2330,CST,77.0,LAUDERDALE,AL,TSTM WIND,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3453.0,8730.0,0.0,0.0,NaN
604.0,1.0,5/14/1967 0:00:00,2330,CST,77.0,LAUDERDALE,AL,TSTM WIND,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3453.0,8730.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900771.0,38.0,10/7/2011 0:00:00,03:00:00 PM,CST,7.0,NDZ007 - 014>016 - 024 - 026>030 - 038>039 - 054,ND,HIGH WIND,0.0,NaN,...,0.0,K,FGF,"NORTH DAKOTA, East",CAVALIER - CAVALIER - BENSON - RAMSEY - EASTER...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong early October low ...
900806.0,27.0,10/7/2011 0:00:00,04:00:00 PM,CST,1.0,MNZ001 - 004>005 - 007>008 - 013,MN,HIGH WIND,0.0,NaN,...,0.0,K,FGF,"MINNESOTA, Northwest",WEST POLK - WEST POLK - KITTSON - ROSEAU - WES...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong early October low ...
900807.0,36.0,10/29/2011 0:00:00,01:00:00 PM,EST,57.0,NYZ057,NY,WINTER STORM,0.0,NaN,...,0.0,K,BGM,"NEW YORK, Central",DELAWARE - DELAWARE,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: An early season winter stor...
900808.0,38.0,10/24/2011 0:00:00,03:03:00 PM,CST,7.0,NDZ007,ND,WILDFIRE,0.0,NaN,...,0.0,K,FGF,"NORTH DAKOTA, East",CAVALIER - CAVALIER,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: Seasonably warm and dry con...
900809.0,27.0,10/5/2011 0:00:00,03:00:00 PM,CST,5.0,MNZ005,MN,WILDFIRE,0.0,NaN,...,0.0,K,FGF,"MINNESOTA, Northwest",ROSEAU - ROSEAU,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A wildfire originated in Ju...

In [92]:
len(df.EVTYPE.unique())

985

In [93]:
df.EVTYPE.unique()

array(['TORNADO', 'TSTM WIND', 'HAIL', 'FREEZING RAIN', 'SNOW',
       'ICE STORM/FLASH FLOOD', 'SNOW/ICE', 'WINTER STORM',
       'HURRICANE OPAL/HIGH WINDS', 'THUNDERSTORM WINDS', 'RECORD COLD',
       'HURRICANE ERIN', 'HURRICANE OPAL', 'HEAVY RAIN', 'LIGHTNING',
       'THUNDERSTORM WIND', 'DENSE FOG', 'RIP CURRENT',
       'THUNDERSTORM WINS', 'FLASH FLOOD', 'FLASH FLOODING', 'HIGH WINDS',
       'FUNNEL CLOUD', 'TORNADO F0', 'THUNDERSTORM WINDS LIGHTNING',
       'THUNDERSTORM WINDS/HAIL', 'HEAT', 'WIND', 'LIGHTING',
       'HEAVY RAINS', 'LIGHTNING AND HEAVY RAIN', 'FUNNEL', 'WALL CLOUD',
       'FLOODING', 'THUNDERSTORM WINDS HAIL', 'FLOOD', 'COLD',
       'HEAVY RAIN/LIGHTNING', 'FLASH FLOODING/THUNDERSTORM WI',
       'WALL CLOUD/FUNNEL CLOUD', 'THUNDERSTORM', 'WATERSPOUT',
       'EXTREME COLD', 'HAIL 1.75)', 'LIGHTNING/HEAVY RAIN', 'HIGH WIND',
       'BLIZZARD', 'BLIZZARD WEATHER', 'WIND CHILL', 'BREAKUP FLOODING',
       'HIGH WIND/BLIZZARD', 'RIVER FLOOD', 'HEAVY SNOW', 'FREEZE',
       'COASTAL FLOOD', 'HIGH WIND AND HIGH TIDES',
       'HIGH WIND/BLIZZARD/FREEZING RA', 'HIGH TIDES',
       'HIGH WIND AND HEAVY SNOW', 'RECORD COLD AND HIGH WIND',
       'RECORD HIGH TEMPERATURE', 'RECORD HIGH', 'HIGH WINDS HEAVY RAINS',
       'HIGH WIND/ BLIZZARD', 'ICE STORM', 'BLIZZARD/HIGH WIND',
       'HIGH WIND/LOW WIND CHILL', 'HEAVY SNOW/HIGH', 'RECORD LOW',
       'HIGH WINDS AND WIND CHILL', 'HEAVY SNOW/HIGH WINDS/FREEZING',
       'LOW TEMPERATURE RECORD', 'AVALANCHE', 'MARINE MISHAP',
       'WIND CHILL/HIGH WIND', 'HIGH WIND/WIND CHILL/BLIZZARD',
       'HIGH WIND/WIND CHILL', 'HIGH WIND/HEAVY SNOW',
       'HIGH TEMPERATURE RECORD', 'FLOOD WATCH/',
       'RECORD HIGH TEMPERATURES', 'HIGH WIND/SEAS',
       'HIGH WINDS/HEAVY RAIN', 'HIGH SEAS', 'SEVERE TURBULENCE',
       'RECORD RAINFALL', 'RECORD SNOWFALL', 'RECORD WARMTH',
       'HEAVY SNOW/WIND', 'EXTREME HEAT', 'WIND DAMAGE', 'DUST STORM',
       'APACHE COUNTY', 'SLEET', 'HAIL STORM', 'FUNNEL CLOUDS',
       'FLASH FLOODS', 'DUST DEVIL', 'EXCESSIVE HEAT',
       'THUNDERSTORM WINDS/FUNNEL CLOU', 'WINTER STORM/HIGH WIND',
       'WINTER STORM/HIGH WINDS', 'GUSTY WINDS', 'STRONG WINDS',
       'FLOODING/HEAVY RAIN', 'SNOW AND WIND',
       'HEAVY SURF COASTAL FLOODING', 'HEAVY SURF', 'HEAVY PRECIPATATION',
       'URBAN FLOODING', 'HIGH SURF', 'BLOWING DUST', 'URBAN/SMALL',
       'WILD FIRES', 'HIGH', 'URBAN/SMALL FLOODING', 'WATER SPOUT',
       'HIGH WINDS DUST STORM', 'WINTER STORM HIGH WINDS', 'LOCAL FLOOD',
       'WINTER STORMS', 'MUDSLIDES', 'RAINSTORM', 'SEVERE THUNDERSTORM',
       'SEVERE THUNDERSTORMS', 'SEVERE THUNDERSTORM WINDS',
       'THUNDERSTORMS WINDS', 'DRY MICROBURST', 'FLOOD/FLASH FLOOD',
       'FLOOD/RAIN/WINDS', 'WINDS', 'DRY MICROBURST 61', 'THUNDERSTORMS',
       'FLASH FLOOD WINDS', 'URBAN/SMALL STREAM FLOODING', 'MICROBURST',
       'STRONG WIND', 'HIGH WIND DAMAGE', 'STREAM FLOODING',
       'URBAN AND SMALL', 'HEAVY SNOWPACK', 'ICE', 'FLASH FLOOD/',
       'DOWNBURST', 'GUSTNADO AND', 'FLOOD/RAIN/WIND', 'WET MICROBURST',
       'DOWNBURST WINDS', 'DRY MICROBURST WINDS', 'DRY MIRCOBURST WINDS',
       'DRY MICROBURST 53', 'SMALL STREAM URBAN FLOOD', 'MICROBURST WINDS',
       'HIGH WINDS 57', 'DRY MICROBURST 50', 'HIGH WINDS 66',
       'HIGH WINDS 76', 'HIGH WINDS 63', 'HIGH WINDS 67',
       'BLIZZARD/HEAVY SNOW', 'HEAVY SNOW/HIGH WINDS', 'BLOWING SNOW',
       'HIGH WINDS 82', 'HIGH WINDS 80', 'HIGH WINDS 58',
       'FREEZING DRIZZLE', 'LIGHTNING THUNDERSTORM WINDSS',
       'DRY MICROBURST 58', 'HAIL 75', 'HIGH WINDS 73', 'HIGH WINDS 55',
       'LIGHT SNOW AND SLEET', 'URBAN FLOOD', 'DRY MICROBURST 84',
       'THUNDERSTORM WINDS 60', 'HEAVY RAIN/FLOODING',
       'THUNDERSTORM WINDSS', 'TORNADOS', 'GLAZE', 'RECORD HEAT',
       'COASTAL FLOODING', 'HEAT WAVE', 'FIRST SNOW',
       'FREEZING RAIN AND SLEET', 'UNSEASONABLY DRY', 'UNSEASONABLY WET',
       'WINTRY MIX', 'WINTER WEATHER', 'UNSEASONABLY COLD',
       'EXTREME/RECORD COLD', 'RIP CURRENTS HEAVY SURF', 'SLEET/RAIN/SNOW',
       'UNSEASONABLY WARM', 'DROUGHT', 'NORMAL PRECIPITATION',
       'HIGH WINDS/FLOODING', 'DRY', 'RAIN/SNOW', 'SNOW/RAIN/SLEET',
       'WATERSPOUT/TORNADO', 'WATERSPOUTS', 'WATERSPOUT TORNADO',
       'URBAN/SMALL STREAM FLOOD', 'STORM SURGE', 'WATERSPOUT-TORNADO',
       'WATERSPOUT-', 'TORNADOES, TSTM WIND, HAIL',
       'TROPICAL STORM ALBERTO', 'TROPICAL STORM', 'TROPICAL STORM GORDON',
       'TROPICAL STORM JERRY', 'LIGHTNING THUNDERSTORM WINDS',
       'WAYTERSPOUT', 'MINOR FLOODING', 'LIGHTNING INJURY',
       'URBAN/SMALL STREAM  FLOOD', 'LIGHTNING AND THUNDERSTORM WIN',
       'THUNDERSTORM WINDS53', 'URBAN AND SMALL STREAM FLOOD',
       'URBAN AND SMALL STREAM', 'WILDFIRE', 'DAMAGING FREEZE',
       'THUNDERSTORM WINDS 13', 'SMALL HAIL', 'HEAVY SNOW/HIGH WIND',
       'HURRICANE', 'WILD/FOREST FIRE', 'SMALL STREAM FLOODING',
       'MUD SLIDE', 'LIGNTNING', 'FROST', 'FREEZING RAIN/SNOW',
       'HIGH WINDS/', 'THUNDERSNOW', 'FLOODS', 'EXTREME WIND CHILLS',
       'COOL AND WET', 'HEAVY RAIN/SNOW', 'SMALL STREAM AND URBAN FLOODIN',
       'SMALL STREAM/URBAN FLOOD', 'SNOW/SLEET/FREEZING RAIN',
       'SEVERE COLD', 'GLAZE ICE', 'COLD WAVE', 'EARLY SNOW',
       'SMALL STREAM AND URBAN FLOOD', 'HIGH  WINDS', 'RURAL FLOOD',
       'SMALL STREAM AND', 'MUD SLIDES', 'HAIL 80', 'EXTREME WIND CHILL',
       'COLD AND WET CONDITIONS', 'EXCESSIVE WETNESS', 'GRADIENT WINDS',
       'HEAVY SNOW/BLOWING SNOW', 'SLEET/ICE STORM',
       'THUNDERSTORM WINDS URBAN FLOOD', 'THUNDERSTORM WINDS SMALL STREA',
       'ROTATING WALL CLOUD', 'LARGE WALL CLOUD', 'COLD AIR FUNNEL',
       'GUSTNADO', 'COLD AIR FUNNELS', 'BLOWING SNOW- EXTREME WIND CHI',
       'SNOW AND HEAVY SNOW', 'GROUND BLIZZARD', 'MAJOR FLOOD',
       'SNOW/HEAVY SNOW', 'FREEZING RAIN/SLEET', 'ICE JAM FLOODING',
       'SNOW- HIGH WIND- WIND CHILL', 'STREET FLOOD', 'COLD AIR TORNADO',
       'SMALL STREAM FLOOD', 'FOG', 'THUNDERSTORM WINDS 2',
       'FUNNEL CLOUD/HAIL', 'ICE/SNOW', 'TSTM WIND 51', 'TSTM WIND 50',
       'TSTM WIND 52', 'TSTM WIND 55', 'HEAVY SNOW/BLIZZARD',
       'THUNDERSTORM WINDS 61', 'HAIL 0.75', 'THUNDERSTORM DAMAGE',
       'THUNDERTORM WINDS', 'HAIL 1.00', 'HAIL/WINDS', 'SNOW AND ICE',
       'WIND STORM', 'SNOWSTORM', 'GRASS FIRES', 'LAKE FLOOD',
       'PROLONG COLD', 'HAIL/WIND', 'HAIL 1.75', 'THUNDERSTORMW 50',
       'WIND/HAIL', 'SNOW AND ICE STORM', 'URBAN AND SMALL STREAM FLOODIN',
       'THUNDERSTORMS WIND', 'THUNDERSTORM  WINDS', 'HEAVY SNOW/SLEET',
       'AGRICULTURAL FREEZE', 'DROUGHT/EXCESSIVE HEAT', 'TUNDERSTORM WIND',
       'TROPICAL STORM DEAN', 'THUNDERTSORM WIND',
       'THUNDERSTORM WINDS/ HAIL', 'THUNDERSTORM WIND/LIGHTNING',
       'HEAVY RAIN/SEVERE WEATHER', 'THUNDESTORM WINDS',
       'WATERSPOUT/ TORNADO', 'LIGHTNING.', 'WARM DRY CONDITIONS',
       'HURRICANE-GENERATED SWELLS', 'HEAVY SNOW/ICE STORM',
       'RIVER AND STREAM FLOOD', 'HIGH WIND 63', 'COASTAL SURGE',
       'HEAVY SNOW AND ICE STORM', 'MINOR FLOOD',
       'HIGH WINDS/COASTAL FLOOD', 'RAIN', 'RIVER FLOODING', 'SNOW/RAIN',
       'ICE FLOES', 'HIGH WAVES', 'SNOW SQUALLS', 'SNOW SQUALL',
       'THUNDERSTORM WIND G50', 'LIGHTNING FIRE', 'BLIZZARD/FREEZING RAIN',
       'HEAVY LAKE SNOW', 'HEAVY SNOW/FREEZING RAIN', 'LAKE EFFECT SNOW',
       'HEAVY WET SNOW', 'DUST DEVIL WATERSPOUT',
       'THUNDERSTORM WINDS/HEAVY RAIN', 'THUNDERSTROM WINDS',
       'THUNDERSTORM WINDS      LE CEN', 'HAIL 225',
       'BLIZZARD AND HEAVY SNOW', 'HEAVY SNOW AND ICE',
       'ICE STORM AND SNOW', 'HEAVY SNOW ANDBLOWING SNOW',
       'HEAVY SNOW/ICE', 'BLIZZARD AND EXTREME WIND CHIL',
       'LOW WIND CHILL', 'BLOWING SNOW & EXTREME WIND CH', 'WATERSPOUT/',
       'URBAN/SMALL STREAM', 'TORNADO F3', 'FUNNEL CLOUD.', 'TORNDAO',
       'HAIL 0.88', 'FLOOD/RIVER FLOOD', 'MUD SLIDES URBAN FLOODING',
       'TORNADO F1', 'THUNDERSTORM WINDS G', 'DEEP HAIL',
       'GLAZE/ICE STORM', 'HEAVY SNOW/WINTER STORM', 'AVALANCE',
       'BLIZZARD/WINTER STORM', 'DUST STORM/HIGH WINDS', 'ICE JAM',
       'FOREST FIRES', 'THUNDERSTORM WIND G60', 'FROST\\FREEZE',
       'THUNDERSTORM WINDS.', 'HAIL 88', 'HAIL 175', 'HVY RAIN',
       'HAIL 100', 'HAIL 150', 'HAIL 075', 'THUNDERSTORM WIND G55',
       'HAIL 125', 'THUNDERSTORM WINDS G60', 'HARD FREEZE', 'HAIL 200',
       'THUNDERSTORM WINDS FUNNEL CLOU', 'THUNDERSTORM WINDS 62',
       'WILDFIRES', 'RECORD HEAT WAVE', 'HEAVY SNOW AND HIGH WINDS',
       'HEAVY SNOW/HIGH WINDS & FLOOD', 'HAIL FLOODING',
       'THUNDERSTORM WINDS/FLASH FLOOD', 'HIGH WIND 70', 'WET SNOW',
       'HEAVY RAIN AND FLOOD', 'LOCAL FLASH FLOOD',
       'THUNDERSTORM WINDS 53', 'FLOOD/FLASH FLOODING',
       'TORNADO/WATERSPOUT', 'RAIN AND WIND', 'THUNDERSTORM WIND 59',
       'THUNDERSTORM WIND 52', 'COASTAL/TIDAL FLOOD', 'SNOW/ICE STORM',
       'BELOW NORMAL PRECIPITATION', 'RIP CURRENTS/HEAVY SURF',
       'FLASH FLOOD/FLOOD', 'EXCESSIVE RAIN', 'RECORD/EXCESSIVE HEAT',
       'HEAT WAVES', 'LIGHT SNOW', 'THUNDERSTORM WIND 69', 'HAIL DAMAGE',
       'LIGHTNING DAMAGE', 'RECORD TEMPERATURES', 'LIGHTNING AND WINDS',
       'FOG AND COLD TEMPERATURES', 'OTHER', 'RECORD SNOW', 'SNOW/COLD',
       'FLASH FLOOD FROM ICE JAMS', 'TSTM WIND G58', 'MUDSLIDE',
       'HEAVY SNOW SQUALLS', 'HEAVY SNOW/SQUALLS', 'HEAVY SNOW-SQUALLS',
       'ICY ROADS', 'HEAVY MIX', 'SNOW FREEZING RAIN', 'LACK OF SNOW',
       'SNOW/SLEET', 'SNOW/FREEZING RAIN', 'SNOW DROUGHT',
       'THUNDERSTORMW WINDS', 'THUNDERSTORM WIND 60 MPH',
       'THUNDERSTORM WIND 65MPH', 'THUNDERSTORM WIND/ TREES',
       'THUNDERSTORM WIND/AWNING', 'THUNDERSTORM WIND 98 MPH',
       'THUNDERSTORM WIND TREES', 'TORRENTIAL RAIN', 'TORNADO F2',
       'RIP CURRENTS', 'HURRICANE EMILY', 'HURRICANE GORDON',
       'HURRICANE FELIX', 'THUNDERSTORM WIND 59 MPH',
       'THUNDERSTORM WINDS 63 MPH', 'THUNDERSTORM WIND/ TREE',
       'THUNDERSTORM DAMAGE TO', 'THUNDERSTORM WIND 65 MPH',
       'FLASH FLOOD - HEAVY RAIN', 'THUNDERSTORM WIND.',
       'FLASH FLOOD/ STREET', 'THUNDERSTORM WIND 59 MPH.',
       'HEAVY SNOW   FREEZING RAIN', 'DAM FAILURE', 'THUNDERSTORM HAIL',
       'HAIL 088', 'THUNDERSTORM WINDSHAIL', 'LIGHTNING  WAUSEON',
       'THUDERSTORM WINDS', 'ICE AND SNOW', 'RECORD COLD/FROST',
       'STORM FORCE WINDS', 'FREEZING RAIN AND SNOW',
       'FREEZING RAIN SLEET AND', 'SOUTHEAST', 'HEAVY SNOW & ICE',
       'FREEZING DRIZZLE AND FREEZING', 'THUNDERSTORM WINDS AND',
       'HAIL/ICY ROADS', 'FLASH FLOOD/HEAVY RAIN',
       'HEAVY RAIN; URBAN FLOOD WINDS;', 'HEAVY PRECIPITATION',
       'TSTM WIND DAMAGE', 'HIGH WATER', 'FLOOD FLASH', 'RAIN/WIND',
       'THUNDERSTORM WINDS 50', 'THUNDERSTORM WIND G52',
       'FLOOD FLOOD/FLASH', 'THUNDERSTORM WINDS 52', 'SNOW SHOWERS',
       'THUNDERSTORM WIND G51', 'HEAT WAVE DROUGHT',
       'HEAVY SNOW/BLIZZARD/AVALANCHE', 'RECORD SNOW/COLD', 'WET WEATHER',
       'UNSEASONABLY WARM AND DRY', 'FREEZING RAIN SLEET AND LIGHT',
       'RECORD/EXCESSIVE RAINFALL', 'TIDAL FLOOD', 'BEACH EROSIN',
       'THUNDERSTORM WIND G61', 'FLOOD/FLASH', 'LOW TEMPERATURE',
       'SLEET & FREEZING RAIN', 'HEAVY RAINS/FLOODING',
       'THUNDERESTORM WINDS', 'THUNDERSTORM WINDS/FLOODING',
       'THUNDEERSTORM WINDS', 'HIGHWAY FLOODING', 'THUNDERSTORM W INDS',
       'HYPOTHERMIA', 'FLASH FLOOD/ FLOOD', 'THUNDERSTORM WIND 50',
       'THUNERSTORM WINDS', 'HEAVY RAIN/MUDSLIDES/FLOOD', 'MUD/ROCK SLIDE',
       'HIGH WINDS/COLD', 'BEACH EROSION/COASTAL FLOOD', 'COLD/WINDS',
       'SNOW/ BITTER COLD', 'THUNDERSTORM WIND 56', 'SNOW SLEET',
       'DRY HOT WEATHER', 'COLD WEATHER', 'RAPIDLY RISING WATER',
       'HAIL ALOFT', 'EARLY FREEZE', 'ICE/STRONG WINDS',
       'EXTREME WIND CHILL/BLOWING SNO', 'SNOW/HIGH WINDS',
       'HIGH WINDS/SNOW', 'EARLY FROST', 'SNOWMELT FLOODING',
       'HEAVY SNOW AND STRONG WINDS', 'SNOW ACCUMULATION',
       'BLOWING SNOW/EXTREME WIND CHIL', 'SNOW/ ICE', 'SNOW/BLOWING SNOW',
       'TORNADOES', 'THUNDERSTORM WIND/HAIL', 'FLASH FLOODING/FLOOD',
       'HAIL 275', 'HAIL 450', 'FLASH FLOOODING', 'EXCESSIVE RAINFALL',
       'THUNDERSTORMW', 'HAILSTORM', 'TSTM WINDS', 'BEACH FLOOD',
       'HAILSTORMS', 'TSTMW', 'FUNNELS', 'TSTM WIND 65)',
       'THUNDERSTORM WINDS/ FLOOD', 'HEAVY RAINFALL', 'HEAT/DROUGHT',
       'HEAT DROUGHT', 'NEAR RECORD SNOW', 'LANDSLIDE',
       'HIGH WIND AND SEAS', 'THUNDERSTORMWINDS',
       'THUNDERSTORM WINDS HEAVY RAIN', 'SLEET/SNOW', 'EXCESSIVE',
       'SNOW/SLEET/RAIN', 'WILD/FOREST FIRES', 'HEAVY SEAS', 'DUSTSTORM',
       'FLOOD & HEAVY RAIN', '?', 'THUNDERSTROM WIND', 'FLOOD/FLASHFLOOD',
       'SNOW AND COLD', 'HOT PATTERN', 'PROLONG COLD/SNOW', 'BRUSH FIRES',
       'SNOW\\COLD', 'WINTER MIX', 'EXCESSIVE PRECIPITATION',
       'SNOWFALL RECORD', 'HOT/DRY PATTERN', 'DRY PATTERN',
       'MILD/DRY PATTERN', 'MILD PATTERN', 'LANDSLIDES', 'HEAVY SHOWERS',
       'HEAVY SNOW AND', 'HIGH WIND 48', 'LAKE-EFFECT SNOW', 'BRUSH FIRE',
       'WATERSPOUT FUNNEL CLOUD', 'URBAN SMALL STREAM FLOOD',
       'SAHARAN DUST', 'HEAVY SHOWER', 'URBAN FLOOD LANDSLIDE',
       'HEAVY SWELLS', 'URBAN SMALL', 'URBAN FLOODS', 'SMALL STREAM',
       'HEAVY RAIN/URBAN FLOOD', 'FLASH FLOOD/LANDSLIDE',
       'LANDSLIDE/URBAN FLOOD', 'HEAVY RAIN/SMALL STREAM URBAN',
       'FLASH FLOOD LANDSLIDES', 'EXTREME WINDCHILL',
       'URBAN/SML STREAM FLD', 'TSTM WIND/HAIL', 'Other',
       'Record dry month', 'Temperature record', 'Minor Flooding',
       'Ice jam flood (minor', 'High Wind', 'Tstm Wind', 'ROUGH SURF',
       'Wind', 'Heavy Surf', 'Dust Devil', 'Wind Damage',
       'Marine Accident', 'Snow', 'Freeze', 'Snow Squalls',
       'Coastal Flooding', 'Heavy Rain', 'Strong Wind', 'COASTAL STORM',
       'COASTALFLOOD', 'Erosion/Cstl Flood', 'Heavy Rain and Wind',
       'Light Snow/Flurries', 'Wet Month', 'Wet Year', 'Tidal Flooding',
       'River Flooding', 'Damaging Freeze', 'Beach Erosion', 'Hot and Dry',
       'Flood/Flash Flood', 'Icy Roads', 'High Surf',
       'Heavy Rain/High Surf', 'Thunderstorm Wind', 'Rain Damage',
       'Unseasonable Cold', 'Early Frost', 'Wintry Mix', 'blowing snow',
       'STREET FLOODING', 'Record Cold', 'Extreme Cold', 'Ice Fog',
       'Excessive Cold', 'Torrential Rainfall', 'Freezing Rain',
       'Landslump', 'Late-season Snowfall', 'Hurricane Edouard',
       'Coastal Storm', 'Flood', 'HEAVY RAIN/WIND', 'TIDAL FLOODING',
       'Winter Weather', 'Snow squalls', 'Strong Winds', 'Strong winds',
       'RECORD WARM TEMPS.', 'Ice/Snow', 'Mudslide', 'Glaze',
       'Extended Cold', 'Snow Accumulation', 'Freezing Fog',
       'Drifting Snow', 'Whirlwind', 'Heavy snow shower', 'Heavy rain',
       'LATE SNOW', 'Record May Snow', 'Record Winter Snow',
       'Heavy Precipitation', ' COASTAL FLOOD', 'Record temperature',
       'Light snow', 'Late Season Snowfall', 'Gusty Wind', 'small hail',
       'Light Snow', 'MIXED PRECIP', 'Black Ice', 'Mudslides',
       'Gradient wind', 'Snow and Ice', 'Freezing Spray', 'Summary Jan 17',
       'Summary of March 14', 'Summary of March 23', 'Summary of March 24',
       'Summary of April 3rd', 'Summary of April 12',
       'Summary of April 13', 'Summary of April 21', 'Summary August 11',
       'Summary of April 27', 'Summary of May 9-10', 'Summary of May 10',
       'Summary of May 13', 'Summary of May 14', 'Summary of May 22 am',
       'Summary of May 22 pm', 'Heatburst', 'Summary of May 26 am',
       'Summary of May 26 pm', 'Metro Storm, May 26',
       'Summary of May 31 am', 'Summary of May 31 pm', 'Summary of June 3',
       'Summary of June 4', 'Summary June 5-6', 'Summary June 6',
       'Summary of June 11', 'Summary of June 12', 'Summary of June 13',
       'Summary of June 15', 'Summary of June 16', 'Summary June 18-19',
       'Summary of June 23', 'Summary of June 24', 'Summary of June 30',
       'Summary of July 2', 'Summary of July 3', 'Summary of July 11',
       'Summary of July 22', 'Summary July 23-24', 'Summary of July 26',
       'Summary of July 29', 'Summary of August 1', 'Summary August 2-3',
       'Summary August 7', 'Summary August 9', 'Summary August 10',
       'Summary August 17', 'Summary August 21', 'Summary August 28',
       'Summary September 4', 'Summary September 20',
       'Summary September 23', 'Summary Sept. 25-26',
       'Summary: Oct. 20-21', 'Summary: October 31', 'Summary: Nov. 6-7',
       'Summary: Nov. 16', 'Microburst', 'wet micoburst', 'Hail(0.75)',
       'Funnel Cloud', 'Urban Flooding', 'No Severe Weather',
       'Urban flood', 'Urban Flood', 'Cold', 'Summary of May 22',
       'Summary of June 6', 'Summary August 4', 'Summary of June 10',
       'Summary of June 18', 'Summary September 3', 'Summary: Sept. 18',
       'Coastal Flood', 'coastal flooding', 'Small Hail',
       'Record Temperatures', 'Light Snowfall', 'Freezing Drizzle',
       'Gusty wind/rain', 'GUSTY WIND/HVY RAIN', 'Blowing Snow',
       'Early snowfall', 'Monthly Snowfall', 'Record Heat',
       'Seasonal Snowfall', 'Monthly Rainfall', 'Cold Temperature',
       'Sml Stream Fld', 'Heat Wave', 'MUDSLIDE/LANDSLIDE', 'Saharan Dust',
       'Volcanic Ash', 'Volcanic Ash Plume', 'Thundersnow shower', 'NONE',
       'COLD AND SNOW', 'DAM BREAK', 'TSTM WIND (G45)',
       'SLEET/FREEZING RAIN', 'BLACK ICE', 'BLOW-OUT TIDES',
       'UNSEASONABLY COOL', 'TSTM HEAVY RAIN', 'Gusty Winds', 'GUSTY WIND',
       'TSTM WIND 40', 'TSTM WIND 45', 'TSTM WIND (41)', 'TSTM WIND (G40)',
       'TSTM WND', 'Wintry mix', ' TSTM WIND', 'Frost', 'Frost/Freeze',
       'RAIN (HEAVY)', 'Record Warmth', 'Prolong Cold', 'Cold and Frost',
       'URBAN/SML STREAM FLDG', 'STRONG WIND GUST', 'LATE FREEZE',
       'BLOW-OUT TIDE', 'Hypothermia/Exposure', 'HYPOTHERMIA/EXPOSURE',
       'Lake Effect Snow', 'Mixed Precipitation', 'Record High',
       'COASTALSTORM', 'Snow and sleet', 'Freezing rain', 'Gusty winds',
       'Blizzard Summary', 'SUMMARY OF MARCH 24-25', 'SUMMARY OF MARCH 27',
       'SUMMARY OF MARCH 29', 'GRADIENT WIND', 'Icestorm/Blizzard',
       'Flood/Strong Wind', 'TSTM WIND AND LIGHTNING', 'gradient wind',
       'Freezing drizzle', 'Mountain Snows', 'URBAN/SMALL STRM FLDG',
       'Heavy surf and wind', 'Mild and Dry Pattern', 'COLD AND FROST',
       'TYPHOON', 'HIGH SWELLS', 'HIGH  SWELLS', 'VOLCANIC ASH',
       'DRY SPELL', ' LIGHTNING', 'BEACH EROSION', 'UNSEASONAL RAIN',
       'EARLY RAIN', 'PROLONGED RAIN', 'WINTERY MIX',
       'COASTAL FLOODING/EROSION', 'HOT SPELL', 'UNSEASONABLY HOT',
       ' TSTM WIND (G45)', 'TSTM WIND  (G45)', 'HIGH WIND (G40)',
       'TSTM WIND (G35)', 'DRY WEATHER', 'ABNORMAL WARMTH',
       'UNUSUAL WARMTH', 'WAKE LOW WIND', 'MONTHLY RAINFALL',
       'COLD TEMPERATURES', 'COLD WIND CHILL TEMPERATURES',
       'MODERATE SNOW', 'MODERATE SNOWFALL', 'URBAN/STREET FLOODING',
       'COASTAL EROSION', 'UNUSUAL/RECORD WARMTH', 'BITTER WIND CHILL',
       'BITTER WIND CHILL TEMPERATURES', 'SEICHE', 'TSTM',
       'COASTAL  FLOODING/EROSION', 'UNSEASONABLY WARM YEAR',
       'HYPERTHERMIA/EXPOSURE', 'ROCK SLIDE', 'ICE PELLETS',
       'PATCHY DENSE FOG', 'RECORD COOL', 'RECORD WARM', 'HOT WEATHER',
       'RECORD TEMPERATURE', 'TROPICAL DEPRESSION', 'VOLCANIC ERUPTION',
       'COOL SPELL', 'WIND ADVISORY', 'GUSTY WIND/HAIL',
       'RED FLAG FIRE WX', 'FIRST FROST', 'EXCESSIVELY DRY',
       'SNOW AND SLEET', 'LIGHT SNOW/FREEZING PRECIP', 'VOG',
       'MONTHLY PRECIPITATION', 'MONTHLY TEMPERATURE', 'RECORD DRYNESS',
       'EXTREME WINDCHILL TEMPERATURES', 'MIXED PRECIPITATION',
       'DRY CONDITIONS', 'REMNANTS OF FLOYD', 'EARLY SNOWFALL',
       'FREEZING FOG', 'LANDSPOUT', 'DRIEST MONTH', 'RECORD  COLD',
       'LATE SEASON HAIL', 'EXCESSIVE SNOW', 'DRYNESS',
       'FLOOD/FLASH/FLOOD', 'WIND AND WAVE', 'LIGHT FREEZING RAIN',
       ' WIND', 'MONTHLY SNOWFALL', 'RECORD PRECIPITATION', 'ICE ROADS',
       'ROUGH SEAS', 'UNSEASONABLY WARM/WET', 'UNSEASONABLY COOL & WET',

In [95]:
df.columns

Index([u'STATE__', u'BGN_DATE', u'BGN_TIME', u'TIME_ZONE', u'COUNTY',
       u'COUNTYNAME', u'STATE', u'EVTYPE', u'BGN_RANGE', u'BGN_AZI',
       u'BGN_LOCATI', u'END_DATE', u'END_TIME', u'COUNTY_END', u'COUNTYENDN',
       u'END_RANGE', u'END_AZI', u'END_LOCATI', u'LENGTH', u'WIDTH', u'F',
       u'MAG', u'FATALITIES', u'INJURIES', u'PROPDMG', u'PROPDMGEXP',
       u'CROPDMG', u'CROPDMGEXP', u'WFO', u'STATEOFFIC', u'ZONENAMES',
       u'LATITUDE', u'LONGITUDE', u'LATITUDE_E', u'LONGITUDE_', u'REMARKS'],
      dtype='object')

In [100]:
df.PROPDMGEXP.notnull().sum()

436363

In [105]:
df = df[(df.FATALITIES > 0) | (df.INJURIES > 0) | df.PROPDMGEXP.notnull() | df.CROPDMGEXP.notnull()]

In [106]:
len(df.EVTYPE.unique())

491

In [111]:
(df.EVTYPE.value_counts() == 1).sum()

247

In [114]:
df['EVTYPE'] = df.EVTYPE.apply(lambda type: type.strip().upper())

In [115]:
len(df.EVTYPE.unique())

447

In [116]:
(df.EVTYPE.value_counts() == 1).sum()

224

In [117]:
official_event_types = [
   'Astronomical Low Tide', 'Avalanche',
   'Blizzard', 'Coastal Flood', 'Cold/Wind Chill', 'Debris Flow',
   'Dense Fog', 'Dense Smoke', 'Drought', 'Dust Devil', 'Dust Storm',
   'Excessive Heat', 'Extreme Cold/Wind Chill', 'Flash Flood', 'Flood',
   'Frost/Freeze', 'Funnel Cloud', 'Freezing Fog', 'Hail', 'Heat',
   'Heavy Rain', 'Heavy Snow', 'High Surf', 'High Wind',
   'Hurricane (Typhoon)', 'Ice Storm', 'Lake-Effect Snow',
   'Lakeshore Flood', 'Lightning', 'Marine Hail', 'Marine High Wind',
   'Marine Strong Wind', 'Marine Thunderstorm Wind', 'Rip Current',
   'Seiche', 'Sleet', 'Storm Surge/Tide', 'Strong Wind',
   'Thunderstorm Wind', 'Tornado', 'Tropical Depression',
   'Tropical Storm', 'Tsunami', 'Volcanic Ash', 'Waterspout', 'Wildfire',
   'Winter Storm', 'Winter Weather',

   # We are also adding 'OTHER'...
   'OTHER'
]

official_event_types = map(lambda type: type.upper(), official_event_types)

In [118]:
official_event_types

['ASTRONOMICAL LOW TIDE',
 'AVALANCHE',
 'BLIZZARD',
 'COASTAL FLOOD',
 'COLD/WIND CHILL',
 'DEBRIS FLOW',
 'DENSE FOG',
 'DENSE SMOKE',
 'DROUGHT',
 'DUST DEVIL',
 'DUST STORM',
 'EXCESSIVE HEAT',
 'EXTREME COLD/WIND CHILL',
 'FLASH FLOOD',
 'FLOOD',
 'FROST/FREEZE',
 'FUNNEL CLOUD',
 'FREEZING FOG',
 'HAIL',
 'HEAT',
 'HEAVY RAIN',
 'HEAVY SNOW',
 'HIGH SURF',
 'HIGH WIND',
 'HURRICANE (TYPHOON)',
 'ICE STORM',
 'LAKE-EFFECT SNOW',
 'LAKESHORE FLOOD',
 'LIGHTNING',
 'MARINE HAIL',
 'MARINE HIGH WIND',
 'MARINE STRONG WIND',
 'MARINE THUNDERSTORM WIND',
 'RIP CURRENT',
 'SEICHE',
 'SLEET',
 'STORM SURGE/TIDE',
 'STRONG WIND',
 'THUNDERSTORM WIND',
 'TORNADO',
 'TROPICAL DEPRESSION',
 'TROPICAL STORM',
 'TSUNAMI',
 'VOLCANIC ASH',
 'WATERSPOUT',
 'WILDFIRE',
 'WINTER STORM',
 'WINTER WEATHER',
 'OTHER']

In [129]:
subset_df = df[df.EVTYPE.isin(official_event_types)]

In [130]:
1. * df.EVTYPE.isin(official_event_types).sum() / len(df)

0.8114550053693942

In [131]:
df[~ df.index.isin(subset_df.index)] .shape

(84451, 36)

In [132]:
todo_df = df[~ df.index.isin(subset_df.index)]

In [133]:
todo_df.EVTYPE.value_counts()

TSTM WIND               65591
THUNDERSTORM WINDS      12080
URBAN/SML STREAM FLD      754
HIGH WINDS                656
TSTM WIND/HAIL            447
                        ...
ROGUE WAVE                  1
MUD SLIDES                  1
COASTAL SURGE               1
LIGHTNING INJURY            1
TUNDERSTORM WIND            1
Name: EVTYPE, dtype: int64

In [134]:
unrecognized_event_types_to_recognized_event_types = {
   'COLD': 'COLD/WIND CHILL',
   'COLD AND SNOW': 'COLD/WIND CHILL',
   'COLD WEATHER': 'COLD/WIND CHILL',
   'EXTREME COLD': 'EXTREME COLD/WIND CHILL',
   'EXTREME HEAT': 'EXCESSIVE HEAT',
   'EXTREME WINDCHILL': 'EXTREME COLD/WIND CHILL',
   'FLASH FLOOD/FLOOD': 'FLASH FLOOD',
   'FLASH FLOODING': 'FLASH FLOOD',
   'FLASH FLOODING/FLOOD': 'FLASH FLOOD',
   'FLOOD/FLASH FLOOD': 'FLASH FLOOD',
   'FLOODING': 'FLOOD',
   'FOG': 'DENSE FOG',
   'FREEZE': 'FROST/FREEZE',
   'FREEZING RAIN': 'HEAVY RAIN',
   'GLAZE': 'OTHER',
   'HEAT WAVE': 'HEAT',
   'HEAT WAVES': 'HEAT',
   'HEAVY RAIN/SEVERE WEATHER': 'HEAVY RAIN',
   'HEAVY SURF': 'HIGH SURF',
   'HEAVY SURF/HIGH SURF': 'HIGH SURF',
   'HIGH SEAS': 'OTHER',
   'HIGH WINDS': 'HIGH WIND',
   'HURRICANE': 'HURRICANE (TYPHOON)',
   'HURRICANE ERIN': 'HURRICANE (TYPHOON)',
   'HURRICANE OPAL': 'HURRICANE (TYPHOON)',
   'HURRICANE/TYPHOON': 'HURRICANE (TYPHOON)',
   'HYPOTHERMIA/EXPOSURE': 'OTHER',
   'ICE': 'ICE STORM',
   'ICY ROADS': 'OTHER',
   'LANDSLIDE': 'OTHER',
   'LOW TEMPERATURE': 'COLD/WIND CHILL',
   'MARINE MISHAP': 'MARINE HAIL',
   'MARINE TSTM WIND': 'MARINE THUNDERSTORM WIND RIP CURRENT',
   'RECORD/EXCESSIVE HEAT': 'EXCESSIVE HEAT',
   'RIP CURRENTS': 'MARINE THUNDERSTORM WIND RIP CURRENT',
   'RIVER FLOOD': 'FLOOD',
   'ROUGH SEAS': 'MARINE STRONG WIND',
   'SEVERE THUNDERSTORM': 'THUNDERSTORM WIND',
   'STORM SURGE': 'STORM SURGE/TIDE',
   'STRONG WINDS': 'STRONG WIND',
   'THUNDERSTORM WINDS': 'THUNDERSTORM WIND',
   'TORNADOES, TSTM WIND, HAIL': 'TORNADO',
   'TROPICAL STORM GORDON': 'TROPICAL STORM',
   'TSTM WIND': 'THUNDERSTORM WIND',
   'TSTM WIND/HAIL': 'THUNDERSTORM WIND',
   'TYPHOON': 'HURRICANE (TYPHOON)',
   'UNSEASONABLY WARM': 'OTHER',
   'UNSEASONABLY WARM AND DRY': 'OTHER',
   'URBAN/SML STREAM FLD': 'FLOOD',
   'WILD FIRES': 'WILDFIRE',
   'WILD/FOREST FIRE': 'WILDFIRE',
   'WIND': 'HIGH WIND',
   'WINTER STORMS': 'WINTER STORM',
   'WINTER WEATHER/MIX': 'WINTER WEATHER'
}

In [137]:

def event_type(event_type):
   if event_type in official_event_types:
       return event_type

   if event_type in unrecognized_event_types_to_recognized_event_types:
       return unrecognized_event_types_to_recognized_event_types[event_type]

   return 'OTHER'

In [140]:
df.EVTYPE.apply(event_type)

REFNUM
1.0            TORNADO
2.0            TORNADO
3.0            TORNADO
4.0            TORNADO
5.0            TORNADO
               ...
902293.0     HIGH WIND
902294.0     HIGH WIND
902295.0     HIGH WIND
902296.0      BLIZZARD
902297.0    HEAVY SNOW
Name: EVTYPE, dtype: object

In [141]:
df['EVTYPE'] = df.EVTYPE.apply(event_type)

In [142]:
1. * df.EVTYPE.isin(official_event_types).sum() / len(df)

1.0

In [143]:
df

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,COUNTYNAME,STATE,EVTYPE,BGN_RANGE,BGN_AZI,...,CROPDMG,CROPDMGEXP,WFO,STATEOFFIC,ZONENAMES,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS
REFNUM,,,,,,,,,,,,,,,,,,,,,
1.0,1.0,4/18/1950 0:00:00,130,CST,97.0,MOBILE,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3040.0,8812.0,3051.0,8806.0,NaN
2.0,1.0,4/18/1950 0:00:00,145,CST,3.0,BALDWIN,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3042.0,8755.0,0.0,0.0,NaN
3.0,1.0,2/20/1951 0:00:00,1600,CST,57.0,FAYETTE,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3340.0,8742.0,0.0,0.0,NaN
4.0,1.0,6/8/1951 0:00:00,900,CST,89.0,MADISON,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3458.0,8626.0,0.0,0.0,NaN
5.0,1.0,11/15/1951 0:00:00,1500,CST,43.0,CULLMAN,AL,TORNADO,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,3412.0,8642.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902293.0,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,WYZ007 - 017,WY,HIGH WIND,0.0,NaN,...,0.0,K,RIW,"WYOMING, Central and West",OWL CREEK & BRIDGER MOUNTAINS - OWL CREEK & BR...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong cold front moved s...
902294.0,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,MTZ009 - 010,MT,HIGH WIND,0.0,NaN,...,0.0,K,TFX,"MONTANA, Central",NORTH ROCKY MOUNTAIN FRONT - NORTH ROCKY MOUNT...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong westerly flow alof...
902295.0,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,AKZ213,AK,HIGH WIND,0.0,NaN,...,0.0,K,AFG,"ALASKA, Northern",ST LAWRENCE IS. BERING STRAIT - ST LAWRENCE IS...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...
902296.0,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,AKZ202,AK,BLIZZARD,0.0,NaN,...,0.0,K,AFG,"ALASKA, Northern",NORTHERN ARCTIC COAST - NORTHERN ARCTIC COAST,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...
902297.0,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,ALZ006,AL,HEAVY SNOW,0.0,NaN,...,0.0,K,HUN,"ALABAMA, North",MADISON - MADISON,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: An intense upper level low ...

In [144]:
df.columns

Index([u'STATE__', u'BGN_DATE', u'BGN_TIME', u'TIME_ZONE', u'COUNTY',
       u'COUNTYNAME', u'STATE', u'EVTYPE', u'BGN_RANGE', u'BGN_AZI',
       u'BGN_LOCATI', u'END_DATE', u'END_TIME', u'COUNTY_END', u'COUNTYENDN',
       u'END_RANGE', u'END_AZI', u'END_LOCATI', u'LENGTH', u'WIDTH', u'F',
       u'MAG', u'FATALITIES', u'INJURIES', u'PROPDMG', u'PROPDMGEXP',
       u'CROPDMG', u'CROPDMGEXP', u'WFO', u'STATEOFFIC', u'ZONENAMES',
       u'LATITUDE', u'LONGITUDE', u'LATITUDE_E', u'LONGITUDE_', u'REMARKS'],
      dtype='object')

In [148]:
df.INJURIES.isnull().sum()

0

In [149]:
df[['PROPDMG','PROPDMGEXP']]

          PROPDMG PROPDMGEXP
REFNUM
1.0          25.0          K
2.0           2.5          K
3.0          25.0          K
4.0           2.5          K
5.0           2.5          K
...           ...        ...
902293.0      0.0          K
902294.0      0.0          K
902295.0      0.0          K
902296.0      0.0          K
902297.0      0.0          K

[447909 rows x 2 columns]

In [167]:
pd.crosstab(df.PROPDMGEXP, df.STATE, dropna = False)

STATE,AK,AL,AM,AN,AR,AS,AZ,CA,CO,CT,...,TX,UT,VA,VI,VT,WA,WI,WV,WY,XX
PROPDMGEXP,,,,,,,,,,,,,,,,,,,,,
+,2,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
-,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,1,0,0,0,0,0,0,3,19,5,...,3,0,21,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
K,1861,14856,1184,2219,10752,102,2825,4863,8141,1559,...,34671,2275,13090,131,2843,1910,9021,5448,3619,2
M,49,313,0,0,406,5,94,349,120,41,...,919,36,195,5,55,111,379,101,24,0
h,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
m,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [168]:
df[['STATE','PROPDMGEXP']]

         STATE PROPDMGEXP
REFNUM
1.0         AL          K
2.0         AL          K
3.0         AL          K
4.0         AL          K
5.0         AL          K
...        ...        ...
902293.0    WY          K
902294.0    MT          K
902295.0    AK          K
902296.0    AK          K
902297.0    AL          K

[447909 rows x 2 columns]

In [169]:
df.PROPDMGEXP.describe()

count     436363
unique        18
top            K
freq      424665
Name: PROPDMGEXP, dtype: object

In [171]:
df.PROPDMGEXP.unique()

array(['K', 'M', nan, 'B', 'm', '+', '0', '5', '6', '?', '4', '2', '3',
       'h', '7', 'H', '-', '1', '8'], dtype=object)

In [175]:
(df.PROPDMGEXP == '?').sum()

8

In [176]:
exponent_to_multiplier = {np.nan: np.nan, '+': np.nan, '-': np.nan, '?': np.nan,
   '0': 10 ** 0,
   '1': 10 ** 1,
   '2': 10 ** 2, 'H': 10 ** 2, 'h': 10 ** 2,
   '3': 10 ** 3,'K': 10 ** 3,'k': 10 ** 3,
   '4': 10 ** 4,
   '5': 10 ** 5,
   '6': 10 ** 6, 'M': 10 ** 6, 'm': 10 ** 6,
   '7': 10 ** 7,
   '8': 10 ** 8,
   'B': 10 ** 9}

In [177]:
df.PROPDMG = df.PROPDMG * df.PROPDMGEXP.map(exponent_to_multiplier)